# Generated by Django 4.2.2 on 2023-06-11 14:49

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_birth_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('prof', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('date_abs', models.DateTimeField()),
                ('justifiee', models.BooleanField()),
                ('motif', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OperationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Vacataire',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('present', models.BooleanField()),
                ('date_presence', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('accounts.user',),
            managers=[
                ('objects', accounts.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('debut', models.DateField()),
                ('fin', models.DateField()),
                ('nbre_heures', models.PositiveIntegerField()),
                ('remuniration', models.DecimalField(decimal_places=2, max_digits=6)),
                ('termes', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.vacataire')),
            ],
        ),
    ]
