# Generated by Django 4.2.2 on 2023-06-11 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_vacataire_dept_alter_vacataire_present'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacataire',
            name='cours',
            field=models.TextField(default=''),
        ),
    ]
